Implement the Login UI
NguyenVanViet2004/FE-GlowUp pull request #12
Opened 2024-09-23 18:28 UTC by truongtdph40209

## Related issues
Resolved #4 

## Summary
Implement the Login UI

## How to test
Run app

## Concern points

## Screenshots
![image](https://github.com/user-attachments/assets/deac81e2-f0e7-44a1-9512-f0331d44283b)

2024-09-24 03:36 UTC, KMTus commented on components/atoms/InputWithIcons.tsx
> +        color={'#156778'}
color ?  Please do not use the code

2024-09-24 03:40 UTC, KMTus commented on components/molecules/InputForm.tsx
> +    <View>
Change the view with tamagui

2024-09-24 03:42 UTC, KMTus commented on constants/Colors.ts
> +    text: '#fff',
text = #fff ?

2024-09-24 03:42 UTC, KMTus commented on constants/Colors.ts
> +    text: '#000',
text = #000 ?

2024-09-24 04:08 UTC, KMTus commented
![image](https://github.com/user-attachments/assets/5e339c8a-8ee0-4941-bb3d-62e40952bbae)
Losing the selection without an account, using Scolllview bar to optimize screens

2024-09-24 04:15 UTC, KMTus commented
![image](https://github.com/user-attachments/assets/76142009-d06e-4d25-b4c1-fe835aa8d93d)
UI ok

2024-09-24 04:41 UTC, truongtdph40209 commented on constants/Colors.ts
> +    text: '#fff',
yes

2024-09-24 04:41 UTC, truongtdph40209 commented on constants/Colors.ts
> +    text: '#000',
yes

2024-09-24 05:12 UTC, KMTus approved these changes

2024-09-24 06:52 UTC, NguyenVanViet2004 requested changes
This PR is terrible. The font family is wrong, the UI doesn't match the design, and miscellaneous names are set for the component...

2024-09-24 08:02 UTC, NguyenVanViet2004 requested changes

2024-09-24 08:02 UTC, NguyenVanViet2004 commented on components/molecules/InputForm.tsx
> +interface Props {
Use `type` instead of `interfaces`, it look like 

```suggestion
type Props =  {
 ....
} & InputProps
```

2024-09-24 08:07 UTC, NguyenVanViet2004 requested changes

2024-09-24 08:07 UTC, NguyenVanViet2004 commented on locales/vi.json
> +        "signup": {
Use cameCase

```suggestion
        "signUp": {
```

2024-09-24 08:07 UTC, NguyenVanViet2004 commented on components/molecules/common/Footer.tsx
> +const Footer: React.FC<Props> = (
`Footer` for what??? Rename

2024-09-24 08:07 UTC, NguyenVanViet2004 commented on components/atoms/TextTitle.tsx
> +export const TextTitle = (props: Props): React.ReactElement => {
Did you mean `Header`?

2024-09-24 08:07 UTC, NguyenVanViet2004 commented on components/atoms/InputWithIcons.tsx
> +
Delete empty space

2024-09-24 08:33 UTC, truongtdph40209 commented on components/atoms/TextTitle.tsx
> +export const TextTitle = (props: Props): React.ReactElement => {
no i don't mean `header`

2024-09-25 10:48 UTC, NguyenVanViet2004 requested changes

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on package.json
Why are there 2 new libraries here? Are they necessary? Where to use?

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on interfaces/Colors.ts
> +  textButton: string
Rename

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on components/molecules/common/Footer.tsx
`Footer` for what?

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on components/templates/LoginTemplate.tsx
> +          <AuthButtonsGroup
Replace `AuthButtonsGroup` with [Separator](https://tamagui.dev/ui/separator)

```suggestion
          <Separator />
```

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on components/molecules/AuthButtonsGroup.tsx
Delete this component, it unnecessary

2024-09-25 10:48 UTC, NguyenVanViet2004 commented on components/atoms/NegativeButton.tsx
> +      backgroundColor={colors.white}
Delete the following two lines of code. After that, you can set the `backgroundColor` and `color` as shown below:

 ```jsx
<NegativeButton backgroundColor="#fff"  color="#fff"/>
```

```suggestion
      backgroundColor={colors.white}
      color={colors.textButton}
```

2024-09-25 13:47 UTC, truongtdph40209 commented on components/molecules/common/Footer.tsx
I use it as a component that contains `text`

2024-09-25 13:55 UTC, truongtdph40209 commented on components/molecules/common/Footer.tsx
i will rename it

2024-09-25 18:07 UTC, KMTus commented on components/atoms/PositiveButton.tsx
> +      pressStyle={{ backgroundColor: colors.gray }}
similar

2024-09-25 18:07 UTC, KMTus commented on components/atoms/InputWithIcons.tsx
> +        fontFamily={'JetBrainsMonoRegular'}
use hook [`useAppFont()`](https://github.com/NguyenVanViet2004/FE-GlowUp/blob/main/components/templates/HomeTemplate.tsx) for set fontFamily

2024-09-26 07:10 UTC, thanhdo29 commented on components/atoms/InputWithIcons.tsx
> +      borderRadius={10}
use size in Constants file

2024-09-26 07:25 UTC, thanhdo29 approved these changes

2024-09-28 10:22 UTC, KMTus approved these changes

2024-09-28 10:29 UTC, thanhdo29 approved these changes

2024-09-28 12:05 UTC, NguyenVanViet2004 approved these changes

2024-09-28 12:06 UTC, merged