Feature/implement the forgot UI
NguyenVanViet2004/FE-GlowUp pull request #15
Opened 2024-09-25 11:06 UTC by KMTus

## Related issues
Resolved #5 

## Summary
- Create template forgot password UI light-dark mode 
- Added new translation keys and new color codes
- Added color at interface and constranst
- Added library Expo LinearGradient  
## How to test
### step 
1. Open app/_layout.tsx 
2. Commet ``` <TamaguiProvider />```
3. Import tempalte ```import ForgotTemplate from '~/components/templates/PorgotPasswordTemplate'``` 
4. Call ```<ForgotTemplate/>```
```return (
    <ForgotTemplate/>
  )```
## Concern points
Is everything perfect? If not, list up concern points

## Screenshots
![image](https://github.com/user-attachments/assets/cdd6601d-d0d4-423a-acc1-98585c48c16a)
![image](https://github.com/user-attachments/assets/418a8f5c-bc38-4c0d-a571-e324d3915727)

2024-09-25 12:55 UTC, NguyenVanViet2004 requested changes

2024-09-25 12:55 UTC, NguyenVanViet2004 commented on components/atoms/NegativeButton.tsx
> +  icon?: JSX.Element
The icon property is already available in [ButtonProps](https://tamagui.dev/ui/button#api-reference), there is no need to add an icon property here. Delete it

```suggestion

  type Props = {
  title: string
  } & ButtonProps

```

2024-09-25 12:55 UTC, NguyenVanViet2004 commented on components/atoms/TextTitle.tsx
> +      fontFamily={'JetBrainsMonoBold'}
use hook [`useAppFont()`](https://github.com/NguyenVanViet2004/FE-GlowUp/blob/main/components/templates/HomeTemplate.tsx) for set fontFamily

2024-09-25 12:55 UTC, NguyenVanViet2004 commented on components/molecules/common/Footer.tsx
> +        color={colors.primaryTeal}
`Footer` for what? Rename

```suggestion
        color={colors.primaryTeal} />
```

2024-09-25 12:55 UTC, NguyenVanViet2004 commented on components/templates/PorgotPasswordTemplate.tsx
`Forgot `not `Porgot`

2024-09-25 12:55 UTC, NguyenVanViet2004 commented on components/templates/PorgotPasswordTemplate.tsx
> +import InputWithIcons from '../atoms/InputWithIcons'
Relative path

2024-09-25 13:53 UTC, thanhdo29 commented on components/atoms/NegativeButton.tsx
> +    <Button
Missing pressStyle property to change color when pressing Button

2024-09-25 13:53 UTC, thanhdo29 commented on components/molecules/InputForm.tsx
> +} & InputProps
I think there is an excess of InputProps here

2024-09-26 07:01 UTC, thanhdo29 approved these changes

2024-09-26 07:25 UTC, thanhdo29 submitted a review, later dismissed

2024-09-26 08:52 UTC, KMTus commented on components/templates/PorgotPasswordTemplate.tsx
> +            <LinearGradient
Surely, I will do that

2024-09-26 15:04 UTC, NguyenVanViet2004 commented
Fix it

![Simulator Screenshot - iPhone 15 Pro - 2024-09-26 at 22 04 06](https://github.com/user-attachments/assets/4986c362-0f42-442f-84f4-926881b8ec2a)

2024-09-27 13:32 UTC, truongtdph40209 commented
![image](https://github.com/user-attachments/assets/5b6d50d5-0451-4c26-8b95-65d09aa2bc41)

2024-09-27 13:33 UTC, truongtdph40209 approved these changes

2024-09-27 15:22 UTC, thanhdo29 approved these changes

2024-09-28 10:21 UTC, truongtdph40209 approved these changes

2024-09-28 10:29 UTC, thanhdo29 approved these changes

2024-09-28 12:07 UTC, NguyenVanViet2004 commented
@KMTus Fix conflicts

2024-09-28 15:35 UTC, truongtdph40209 approved these changes

2024-09-28 15:38 UTC, thanhdo29 approved these changes

2024-09-30 01:21 UTC, NguyenVanViet2004 approved these changes

2024-09-30 01:21 UTC, merged