Implement the sign up UI
NguyenVanViet2004/FE-GlowUp pull request #16
Opened 2024-09-28 15:56 UTC by truongtdph40209

## Related issues
Resolved #4 

## Summary
Implement the sign up UI

## How to test
### Steps:
1. Open `Index.js` and delete the code in render
2. **Paste** the following line:

```jsx
<SignUpTemplate/>
```
3. Run app

## Concern points

## Screenshots
| Light mode | Dark mode |
| --- | --- |
|![image](https://github.com/user-attachments/assets/c4d8b42c-da28-4e1d-8d2c-94fe9b5eeb5b)|![image](https://github.com/user-attachments/assets/86b06c57-e3d1-436a-85a0-38ec59ce0491)|

2024-09-30 01:23 UTC, NguyenVanViet2004 requested changes

2024-09-30 01:23 UTC, NguyenVanViet2004 commented on app/authentication/Signup.tsx
`SignUp` not `Signup`

2024-10-01 07:07 UTC, NguyenVanViet2004 requested changes
Rebase not merge

![image](https://github.com/user-attachments/assets/7e55b401-bbf2-44a8-82c9-a6240233ba1d)

2024-10-02 01:51 UTC, NguyenVanViet2004 requested changes
Delete constant SPACING_20 now

<img width="425" alt="Ảnh màn hình 2024-10-02 lúc 08 48 05" src="https://github.com/user-attachments/assets/0ba8533a-4773-4a25-8dae-0eafa5ea41b4">

2024-10-02 01:51 UTC, NguyenVanViet2004 commented on components/templates/SignUpTemplate.tsx
> +  const ButtonSignUp = (): void => {
Function's name???

2024-10-04 12:32 UTC, KMTus approved these changes

2024-10-05 01:31 UTC, thanhdo29 approved these changes

2024-10-05 01:38 UTC, NguyenVanViet2004 approved these changes

2024-10-05 01:39 UTC, merged