Fix/Change the language for content OnboardingTemplate
NguyenVanViet2004/FE-GlowUp pull request #32
Opened 2024-10-07 11:42 UTC by thanhdo29

## Related issues

## Summary
Change the languages for content

## How to test
Go to your device's settings to change the language

## Concern points
## Screenshots
![z5861990898363_b2af93826a3f3037659375f887bb543d](https://github.com/user-attachments/assets/b3470e0d-8ba4-4302-857b-1cb6ca0054b2)
![Uploading z5905975494622_eec2370ddb3473e10c339c89bf9b3936.jpg…]()

2024-10-07 14:24 UTC, NguyenVanViet2004 commented
Create issue for this PR

2024-10-07 15:14 UTC, truongtdph40209 submitted a review, later dismissed

2024-10-08 04:09 UTC, NguyenVanViet2004 requested changes

2024-10-08 04:09 UTC, NguyenVanViet2004 commented on app/index.tsx
> +      router.replace('/authentication/Login')
redirect to home

2024-10-08 04:09 UTC, NguyenVanViet2004 commented on components/templates/OnboardingTemplate.tsx
> +const Paginator = (
Can you separate this function into a separate file?

2024-10-08 13:58 UTC, NguyenVanViet2004 approved these changes

2024-10-10 02:43 UTC, KMTus commented
![image](https://github.com/user-attachments/assets/730b914b-36d1-4c82-a4fc-6bea80ed5e7d)
successful check

2024-10-10 02:44 UTC, KMTus approved these changes

2024-10-10 13:07 UTC, merged