Implement Reset password UI
NguyenVanViet2004/FE-GlowUp pull request #35
Opened 2024-10-07 16:21 UTC by truongtdph40209

## Related issues
Resolved #28 

## Summary
- Implement ResetPassword screen includes: 
   + Enter new password and confirm
   + Dark mode, light mode
- Update translation key 
- Add router ResetPassword and ForgotPassword

## How to test
### Steps:
1. Open `Index.js` and delete the code in render
2. **Paste** the following line:

```jsx
<ResetPasswordTemplate/>
```
3. Run app

## Concern points

## Screenshots
| Light mode | Dark mode |
| --- | --- |
|![image](https://github.com/user-attachments/assets/c06b7e3e-f0b4-472e-896e-12af4384cc0d)|![image](https://github.com/user-attachments/assets/69ce6c32-6f91-414a-8caf-f93a7867a840)|

2024-10-08 13:56 UTC, NguyenVanViet2004 commented
![Simulator Screenshot - iPhone 15 Pro - 2024-10-08 at 20 52 54](https://github.com/user-attachments/assets/29df84e4-1ba8-477e-90e2-e22d56650344)


where is the back icon and icon eye for the hidden password?

2024-10-10 02:49 UTC, KMTus commented on components/templates/ResetPasswordTemplate.tsx
We need a function to check the right or wrong conditions of the password, interface or notice if they do not match (can be used to display status or use modal)

2024-10-11 14:06 UTC, NguyenVanViet2004 requested changes
Update the password reset image in this PR content

2024-11-12 01:34 UTC, NguyenVanViet2004 requested changes
API?

2024-11-13 02:14 UTC, NguyenVanViet2004 approved these changes

2024-11-13 02:14 UTC, merged