Implement the home UI
NguyenVanViet2004/FE-GlowUp pull request #37
Opened 2024-10-09 06:26 UTC by thanhdo29

## Related issues
Resolve #24 

## Summary
## How to test
- Run app
- Switch dark mode and light mode on your device

## Concern points
Runs on dark mode and light mode

## Screenshots
<img src="https://github.com/user-attachments/assets/5bca8586-69ef-4ba8-8ed5-959aff60cde8" width="150" height="300"/>

<img src="https://github.com/user-attachments/assets/74541a3c-47c1-424c-b27a-d97fefedf658" width="150" height="300"/>

2024-10-10 03:01 UTC, KMTus commented
![image](https://github.com/user-attachments/assets/2b218c1b-714b-4d45-ae3e-2ebb8a842d17)
Can you make a banner like this?

2024-10-10 13:13 UTC, NguyenVanViet2004 requested changes
There are so many bugs

![Simulator Screenshot - iPhone 15 Pro Max - 2024-10-10 at 20 10 48](https://github.com/user-attachments/assets/97e179dc-78aa-4b1c-82ff-5ec4fe530bda)

2024-10-12 01:32 UTC, NguyenVanViet2004 requested changes
![Simulator Screenshot - iPhone 16 Plus - 2024-10-12 at 08 31 03](https://github.com/user-attachments/assets/2b0d4bf8-4b30-4a3a-9112-e67fbc7e13d8)

2024-10-12 01:43 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/459ef1f2-a7dc-47a3-a7a6-89c8e15fd0ab)

2024-10-12 04:16 UTC, thanhdo29 commented
> ![image](https://private-user-images.githubusercontent.com/132866307/375915219-459ef1f2-a7dc-47a3-a7a6-89c8e15fd0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDYzNTUsIm5iZiI6MTcyODcwNjA1NSwicGF0aCI6Ii8xMzI4NjYzMDcvMzc1OTE1MjE5LTQ1OWVmMWYyLWE3ZGMtNDdhMy1hN2E2LTg5YzhlMTVmZDBhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2Y5NmYyNTQwMGNmYjI4N2VlM2QwMjNjMTdlYjM1ZmU3MzI0YTVhMDI4MzNjZTdjZGEwNWZlZTE1ODI5NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G5FVNfVTZOIW6VikImJpqSWjV4ML-1PlUGg9O4D6jMU)



> ![image](https://private-user-images.githubusercontent.com/132866307/375915219-459ef1f2-a7dc-47a3-a7a6-89c8e15fd0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDYzNTUsIm5iZiI6MTcyODcwNjA1NSwicGF0aCI6Ii8xMzI4NjYzMDcvMzc1OTE1MjE5LTQ1OWVmMWYyLWE3ZGMtNDdhMy1hN2E2LTg5YzhlMTVmZDBhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2Y5NmYyNTQwMGNmYjI4N2VlM2QwMjNjMTdlYjM1ZmU3MzI0YTVhMDI4MzNjZTdjZGEwNWZlZTE1ODI5NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G5FVNfVTZOIW6VikImJpqSWjV4ML-1PlUGg9O4D6jMU)

I don't understand the View All part. Do you mean to display the selected Combo on the Banner?

2024-10-14 07:38 UTC, NguyenVanViet2004 commented
@thanhdo29  No, I want to redirect the user to a new template when the user clicks "View all" to show all combos

2024-11-11 14:53 UTC, NguyenVanViet2004 requested changes
Call api to display combo

2024-11-17 03:03 UTC, KMTus approved these changes

2024-11-17 04:29 UTC, truongtdph40209 reviewed
Fix notification icon for darkmode
![image](https://github.com/user-attachments/assets/055be27b-4fe2-4a25-b5bb-75c4802fe9e9)

2024-11-17 04:29 UTC, truongtdph40209 commented on components/templates/HomeTemplate.tsx
> +          />
Use api banner

2024-11-17 04:29 UTC, truongtdph40209 commented on components/templates/HomeTemplate.tsx
> +import Loading from '../atoms/Loading'
Relative path

2024-11-17 16:17 UTC, truongtdph40209 reviewed
You should pull the latest code from the backend

2024-11-17 16:17 UTC, truongtdph40209 commented on apis/HttpClient.ts
> +  data: T
![image](https://github.com/user-attachments/assets/879b532e-83ab-4d87-9ed2-803e6c94f699)
Update inteface

2024-11-17 16:17 UTC, truongtdph40209 commented on hooks/useFetchBanner.ts
> +          setBanner(response.data)
Sync with backend

2024-11-17 16:17 UTC, truongtdph40209 commented on hooks/useFetchCombo.ts
> +          setCombos(response.data)
Sync with backend data => result

2024-11-19 15:03 UTC, NguyenVanViet2004 approved these changes

2024-11-19 15:03 UTC, merged