Implement Notification UI
NguyenVanViet2004/FE-GlowUp pull request #70
Opened 2024-12-05 03:44 UTC by truongtdph40209

## Related issues
Resolved #69 

## Summary
- Implement the Notification  UI
- Implement the Change Password UI
- Update View Booking

## How to test
- Run the app and tap on your notification icon
- Go to Profile and select change password
- Go to booking and click on view voucher button (make sure your account has data or you can log in with account {acccount: 0327367649, password: 123456})

## Concern points

## Screenshots
![image](https://github.com/user-attachments/assets/589ca880-d9d7-40b0-9631-9e1952f6c5ea)
![image](https://github.com/user-attachments/assets/6c24a12c-a731-45ca-a4a6-f53c67e3d385)
![image](https://github.com/user-attachments/assets/98cc0b2c-b7a1-4d52-ad16-9ff848bad09c)

2024-12-05 11:04 UTC, KMTus approved these changes

2024-12-06 04:58 UTC, NguyenVanViet2004 requested changes
| Status | Comment | Screenshot |
| --- | --- | --- |
| PENDING | disable radio button | ![Simulator Screenshot - iPhone 16 Plus - 2024-12-06 at 11 49 43](https://github.com/user-attachments/assets/a02134aa-734b-4e01-ad54-4eae345235e5)|
| DONE | show a radio button to show the payment method the user paid with ( still disable to block user click ) | ![Simulator Screenshot - iPhone 16 Plus - 2024-12-06 at 11 52 01](https://github.com/user-attachments/assets/e0b77ca2-a5ab-40e6-9590-8356691737bb)|
| CACCLED | Add button `Xem phiếu` like tab `Done` and `Pending` to view detail | ![Simulator Screenshot - iPhone 16 Plus - 2024-12-06 at 11 56 55](https://github.com/user-attachments/assets/7fd9f339-9c71-48e7-baee-859da743939c)|

2024-12-06 05:02 UTC, NguyenVanViet2004 requested changes
I logged into your account but when I redirect  to the notification screen, I don't see any notifications, nothing at all.

2024-12-06 15:00 UTC, NguyenVanViet2004 approved these changes

2024-12-06 15:00 UTC, merged