Bugfix/loading when data canceling booking
NguyenVanViet2004/FE-GlowUp pull request #84
Opened 2024-12-11 05:33 UTC by thanhdo29

## Related issues
Resolve #79 

## Summary

- Fix duplicate id radio button error
- Cancel booking without reloading data
- Update profile information in redux, storage, server

## How to test

## Concern points

## Screenshots

2024-12-11 07:42 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/359f9b14-13eb-404f-a889-eb0e846ab726)

2024-12-11 07:45 UTC, NguyenVanViet2004 requested changes
![image](https://github.com/user-attachments/assets/cc9d9676-89b2-4032-8579-706eec92f977)

I chose the online payment option, but when I checked the appointment ticket, the payment method showed as cash?

2024-12-11 08:04 UTC, NguyenVanViet2004 commented
Please reformat the currency to VND
![Simulator Screenshot - iPhone 16 Plus - 2024-12-11 at 15 03 24](https://github.com/user-attachments/assets/0596d6ff-ac99-4a9d-9e99-049141c2e307)

2024-12-11 08:06 UTC, thanhdo29 commented
Here I check if the user selects but has not yet transferred money, I still show the radiobutton

2024-12-12 03:58 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/69ea2442-9bef-442f-85da-651bde778f78)
![image](https://github.com/user-attachments/assets/d3a5d7d7-d9ff-4883-9e21-12d8101f9ffb)
![image](https://github.com/user-attachments/assets/10221e23-4168-418d-a65e-89947621c53e)

2024-12-12 04:08 UTC, NguyenVanViet2004 requested changes

2024-12-12 04:08 UTC, NguyenVanViet2004 commented on components/molecules/BookingUpcoming.tsx
> +  )
`.reverse()`

2024-12-12 04:23 UTC, NguyenVanViet2004 requested changes
Replace this code block 
```html
<typeStyles.icon
      size={40}
      color={colors.white}
      alignSelf="center"
      padding={25}
      borderRadius={50}
      backgroundColor={typeStyles.color}
/>
```
with
```html
<View
    alignSelf='center'
    borderRadius={50}
    backgroundColor={typeStyles.color}>
    <typeStyles.icon size={50} color={colors.white} />
</View>
```

in [AppModal](https://github.com/NguyenVanViet2004/FE-GlowUp/blob/main/components/molecules/common/AppModal.tsx) to fix this bug (only occurs on ios device):
![image](https://github.com/user-attachments/assets/aecc9360-06bc-4f1e-8769-09aca46bd131)

2024-12-13 04:39 UTC, NguyenVanViet2004 requested changes
> [!IMPORTANT]
> CRASH APP 

![Simulator Screen Recording - iPhone 16 Plus - 2024-12-13 at 11 38 13](https://github.com/user-attachments/assets/654bcc5a-8065-4ec3-b00e-cd56a73b762c)

2024-12-13 04:50 UTC, NguyenVanViet2004 commented
![image](https://github.com/user-attachments/assets/50a27b4d-ce86-49be-b8ca-d7fbd3a5348f)

2024-12-15 03:56 UTC, NguyenVanViet2004 commented
| --- |
| --- |
|![image](https://github.com/user-attachments/assets/72eb80a8-0bdb-4ddb-929e-ff2eefab9f19)||







https://github.com/user-attachments/assets/33896cb8-f8ac-4010-83a9-79d461d72b63


https://github.com/user-attachments/assets/7db5e426-1e6c-40fd-9664-20d9d000920f

2024-12-15 03:57 UTC, NguyenVanViet2004 requested changes
Fix

2024-12-15 08:52 UTC, truongtdph40209 approved these changes

2024-12-15 08:54 UTC, NguyenVanViet2004 approved these changes

2024-12-15 08:54 UTC, merged